'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');const core=require('../src/core.js');const demo=require('../src/demo-config.js');const copy=()=>JSON.parse(JSON.stringify(demo));
test('prepare previews detached config; cancel preserves selected team and serialized registry',()=>{const registry=core.createTeamRegistry(null,demo),before=registry.serialize(),c=copy();c.team.name='Another sample';const preview=registry.prepare(JSON.stringify(c));assert.equal(preview.team.name,c.team.name);preview.team.name='Changed';assert.equal(registry.current().team.name,demo.team.name);assert.equal(registry.serialize(),before);registry.cancel();assert.equal(registry.serialize(),before);assert.throws(()=>registry.apply());});
test('apply, reload and team selection preserve separate history namespaces',()=>{let registry=core.createTeamRegistry(null,demo);const firstKey=core.storageKey(demo),c=copy();c.team.id='another-studio';c.team.name='Other Studio';registry.prepare(JSON.stringify(c));registry.apply();assert.equal(registry.current().team.id,'another-studio');const otherKey=core.storageKey(c);assert.notEqual(firstKey,otherKey);registry=core.createTeamRegistry(registry.serialize(),demo);assert.equal(registry.current().team.id,'another-studio');assert.equal(registry.list().length,2);registry.select(firstKey);assert.equal(registry.current().team.id,demo.team.id);const storage=new Map(),first=core.seedState(demo),other=core.seedState(c);core.appendLocalMessage(first,demo,demo.team.leadRoleId,'First team note',false);core.appendLocalMessage(other,c,c.team.leadRoleId,'Other team note',false);storage.set(firstKey,JSON.stringify(first));storage.set(otherKey,JSON.stringify(other));assert.equal(core.restoreState(storage.get(firstKey),demo).state.messages[demo.team.leadRoleId][0].text,'First team note');assert.equal(core.restoreState(storage.get(otherKey),c).state.messages[c.team.leadRoleId][0].text,'Other team note');});
test('malformed, oversized and credential/prototype configurations cannot apply or persist',()=>{const registry=core.createTeamRegistry(null,demo),before=registry.serialize();const credential=copy();credential.roles[0].apiKey='demo';const dangerous=JSON.stringify(demo).replace('"schemaVersion":','"__proto__":{},"schemaVersion":');for(const raw of ['{','x'.repeat(65537),JSON.stringify(credential),dangerous]){assert.throws(()=>registry.prepare(raw));assert.throws(()=>registry.apply());assert.equal(registry.serialize(),before);}});
test('deep structures reject before activation and hostile markup stays literal',()=>{const registry=core.createTeamRegistry(null,demo),deep=copy();let nested={};deep.extra=nested;for(let i=0;i<15;i++){nested.next={};nested=nested.next;}assert.throws(()=>registry.prepare(JSON.stringify(deep)),/structure limit/);const c=copy();c.roles[0].name='<script>alert(1)</script>';c.roles[0].responsibility='<img src=x onerror=alert(1)>';const preview=registry.prepare(JSON.stringify(c));assert.equal(preview.roles[0].name,c.roles[0].name);registry.apply();assert.equal(registry.current().roles[0].responsibility,c.roles[0].responsibility);});
test('supports arbitrary schema-valid 1 to 24 roles and enforces registry bound',()=>{const c=copy();c.roles=Array.from({length:24},(_,i)=>({...copy().roles[0],id:'role-'+i,name:'Role '+i}));c.team.leadRoleId='role-0';c.tasks=[];assert.equal(core.validateConfig(c).roles.length,24);c.roles.push({...c.roles[0],id:'overflow'});assert.throws(()=>core.validateConfig(c));const registry=core.createTeamRegistry(null,demo);for(let i=1;i<8;i++){const next=copy();next.team.id='sample-'+i;registry.prepare(JSON.stringify(next));registry.apply();}const ninth=copy();ninth.team.id='sample-nine';assert.throws(()=>registry.prepare(JSON.stringify(ninth)),/limit/);assert.equal(registry.list().length,8);});
test('corrupt or credential-bearing persisted registry falls back to fictional default',()=>{for(const raw of ['{',JSON.stringify({version:1,selected:'bad',teams:[{apiKey:'demo'}]}),'x'.repeat(600001)])assert.deepEqual(core.createTeamRegistry(raw,demo).current(),demo);});
test('import UI has explicit review/apply/cancel and safe local-only rendering hooks',()=>{const html=fs.readFileSync('index.html','utf8'),app=fs.readFileSync('src/app.js','utf8');for(const id of ['import-file','import-preview','import-fields','import-apply','import-cancel','local-team-select'])assert.ok(html.includes('id="'+id+'"'));assert.match(html,/id="import-apply" disabled/);assert.match(app,/file.size>core.CONFIG_BYTES/);assert.match(app,/registry.prepare\(text\)/);assert.match(app,/registry.apply\(\)/);assert.match(app,/registry.cancel\(\)/);assert.match(app,/import-fields'\)\.textContent/);assert.doesNotMatch(app,/innerHTML|fetch\s*\(|XMLHttpRequest|WebSocket|eval\s*\(/);});
