'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');const {RolequiltLiveClient}=require('../bridge/live-ui.js');
test('same live UI handler enforces pairing, blocks duplicate turn, surfaces failures without mock',async()=>{let resolve,calls=[];const client=new RolequiltLiveClient(async(route,options)=>{calls.push({route,options});if(route==='/session')return {ok:true,json:async()=>({session:'fixture'})};return new Promise(r=>{resolve=r;});});await assert.rejects(client.send('one','Hello','fixture'),/Pair/);await client.pair();const pending=client.send('one','Hello','fixture');await assert.rejects(client.send('one','Again','fixture'),/pending/);assert.equal(JSON.parse(calls.at(-1).options.body).roleId,'one');resolve({ok:false,json:async()=>({error:'Runtime unavailable'})});await assert.rejects(pending,/unavailable/);assert.equal(client.pending,false);});
test('live persisted messages restore by role and static demo remains network disconnected',()=>{const core=require('../src/core.js'),demo=require('../src/demo-config.js');const state=core.seedState(demo);state.messages[demo.roles[0].id].push({type:'live',text:'Verified runtime fixture',time:10});assert.equal(core.restoreState(JSON.stringify(state),demo).state.messages[demo.roles[0].id][0].type,'live');assert.equal(core.restoreState(JSON.stringify(state),demo).state.messages[demo.roles[1].id].length,0);assert.match(fs.readFileSync('index.html','utf8'),/connect-src 'none'/);assert.doesNotMatch(fs.readFileSync('index.html','utf8'),/bridge\/live-ui/);const source=fs.readFileSync('bridge/live-ui.js','utf8');assert.match(source,/stopImmediatePropagation/);assert.match(source,/mode.value==='demo'/);assert.match(source,/No mock reply generated/);});
test('browser-like fetch keeps its Window receiver through pair, connect, stream polling and errors',async()=>{let count=0;function receiverSensitiveFetch(route,options){if(this!==globalThis)throw TypeError('Illegal invocation');count++;const action=JSON.parse(options.body).action;if(route==='/session')return Promise.resolve({ok:true,json:async()=>({session:'fixture'})});if(action==='start')return Promise.resolve({ok:false,json:async()=>({error:'Fixture runtime error'})});return Promise.resolve({ok:true,json:async()=>({status:'ready',events:action==='state'?[{type:'delta',data:{roleId:'one',delta:'Fixture stream'}}]:[]})});}const client=new RolequiltLiveClient(receiverSensitiveFetch);await client.pair();assert.equal((await client.action('enable')).status,'ready');assert.equal((await client.action('state')).events[0].data.delta,'Fixture stream');await assert.rejects(client.send('one','Hello','fixture'),/Fixture runtime error/);assert.equal(client.pending,false);assert.equal(count,4);});

test('role model preferences require discovered models and never silently fall back',()=>{const catalog=[{id:'fixture-id',model:'fixture-model'}];assert.equal(RolequiltLiveClient.resolveModel({provider:'openai',modelId:'fixture-model'},catalog,'fallback'),'fixture-id');assert.throws(()=>RolequiltLiveClient.resolveModel({provider:'openai',modelId:'unavailable'},catalog,'fallback'),/unavailable/);assert.equal(RolequiltLiveClient.resolveModel({provider:'none',modelId:''},catalog,'fixture-id'),'fixture-id');assert.equal(RolequiltLiveClient.resolveModel({provider:'anthropic',modelId:'fixture-model'},catalog,'fallback','anthropic'),'fixture-id');assert.throws(()=>RolequiltLiveClient.resolveModel({provider:'anthropic',modelId:''},catalog,'fallback','openai'),/not connected/);assert.throws(()=>RolequiltLiveClient.resolveModel({provider:'openai',modelId:'fixture-model'},catalog,'fallback','anthropic'),/not connected/);});
test('expired pairing resets client authorization and supports fresh pair recovery',async()=>{let denied=true;const client=new RolequiltLiveClient(async route=>({status:route==='/action'&&denied?403:200,ok:route!=='/action'||!denied,json:async()=>route==='/session'?{session:'fixture'}:{error:'Session rejected',status:'ready'}}));await client.pair();await assert.rejects(client.action('state'),/Session rejected/);assert.equal(client.session,null);assert.equal(client.pending,false);denied=false;await client.pair();assert.equal((await client.action('enable')).status,'ready');});


test('composer consultation intent routes only direct requests to one exact same-team teammate',()=>{
 const roles=[{id:'lead',name:'Lead'},{id:'reviewer',name:'Review Partner'},{id:'scout',name:'Scout'}],intent=text=>RolequiltLiveClient.consultationIntent(text,roles,'lead');
 for(const text of ['Consult Review Partner about this','Please ask Review Partner to review this','Can you talk with reviewer about the plan?','Lead, could you check with Review Partner?','I would like you to speak to reviewer about this','Get feedback from REVIEW PARTNER'])assert.deepEqual(intent(text),{type:'consult',recipientId:'reviewer'},text);
 for(const text of ['Ask the other agent','Consult an external person','Ask Review Partner and Scout','Ask Review Partner to consult Scout','Consult Lead','Consult Review Partner and another person','Consult Review Partners'])assert.equal(intent(text).type,'clarify',text);
 for(const text of ['Hello','Tell me how to consult Review Partner','Do not ask Review Partner','Yesterday I asked Review Partner','"Consult Review Partner"','> Ask Review Partner','Here is a prompt:\nConsult Review Partner','Can you ask me three questions?','Ask why this happened'])assert.equal(intent(text).type,'chat',text);
 assert.equal(RolequiltLiveClient.consultationIntent('Ask Duplicate',roles.concat([{id:'a',name:'Duplicate'},{id:'b',name:'Duplicate'}]),'lead').type,'clarify');
 assert.deepEqual(RolequiltLiveClient.consultationIntent('Consult A+B about this',[{id:'lead',name:'Lead'},{id:'special',name:'A+B'}],'lead'),{type:'consult',recipientId:'special'});
 assert.equal(RolequiltLiveClient.consultationIntent('Consult Review Partner',[{id:'lead',name:'Lead'}],'lead').type,'clarify');
 assert.deepEqual(RolequiltLiveClient.consultationIntent('Consult Cafe\u0301 about this',[{id:'lead',name:'Lead'},{id:'accent',name:'Café'}],'lead'),{type:'consult',recipientId:'accent'});
});
test('consultation client uses existing protected endpoint and reports failures without spawning ordinary chat',async()=>{
 const actions=[],client=new RolequiltLiveClient(async(route,options)=>{const body=JSON.parse(options.body);actions.push(body);return {ok:route==='/session',json:async()=>route==='/session'?{session:'fixture'}:{error:'Recipient unavailable'}};});
 await client.pair();await assert.rejects(client.consult('lead','reviewer','Consult Review Partner','fixture','fixture'),/Recipient unavailable/);assert.equal(client.pending,false);assert.equal(actions.filter(x=>x.action==='consult').length,1);assert.equal(actions.filter(x=>x.action==='start').length,0);
});

test('chat consultation messages attribute real teammate replies and retain partial/disconnected states',()=>{const roles=[{id:'lead',name:'Lead'},{id:'reviewer',name:'Reviewer'}],base={id:'fixture-relay',sourceId:'lead',recipientId:'reviewer',teamKey:'fixture-team',time:10,reply:'Actual fixture reply',phase:'response'};const reply=RolequiltLiveClient.consultationMessages({...base,type:'reply',stage:'response'},roles);assert.equal(reply[0].roleId,'lead');assert.equal(reply[0].speakerId,'reviewer');assert.equal(reply[0].text,'Actual fixture reply');const stopped=RolequiltLiveClient.consultationMessages({...base,type:'finished',stage:'disconnected',reason:'Runtime disconnected'},roles);assert.match(stopped[1].text,/follow-up did not complete/);assert.doesNotMatch(stopped[1].text,/cancelled/);assert.equal(stopped[0].partial,false);const partial=RolequiltLiveClient.consultationMessages({...base,type:'finished',phase:'request',stage:'cancelled'},roles);assert.equal(partial[0].partial,true);const core=require('../src/core.js'),demo=require('../src/demo-config.js'),state=core.seedState(demo),r=demo.roles;state.messages[r[0].id].push({type:'live',text:'Preserved reply',speakerId:r[1].id,messageId:'fixture:reply',partial:true,time:10},{type:'status',text:'Disconnected; reply retained',messageId:'fixture:progress',time:11});const restored=core.restoreState(JSON.stringify(state),demo).state.messages[r[0].id];assert.equal(restored[0].speakerId,r[1].id);assert.equal(restored[0].messageId,'fixture:reply');assert.equal(restored[0].partial,true);assert.equal(restored[1].type,'status');});

test('late expired response from old pairing cannot revoke a new browser session',async()=>{let finish;const client=new RolequiltLiveClient(async route=>route==='/session'?{ok:true,json:async()=>({session:'fixture-new'})}:new Promise(resolve=>finish=resolve));await client.pair();const old=client.action('state');await client.pair();finish({ok:false,status:403,json:async()=>({error:'Session rejected'})});await assert.rejects(old,error=>error.stale===true);assert.equal(client.session,'fixture-new');});
test('combined catalogs route each role preference to its own runtime',()=>{const catalog=[{id:'openai:fixture-a',model:'fixture-a',runtime:'openai'},{id:'anthropic:fixture-b',model:'fixture-b',runtime:'anthropic'},{id:'anthropic:fixture-c',model:'fixture-c',runtime:'anthropic'}];assert.equal(RolequiltLiveClient.resolveModel({provider:'anthropic',modelId:'fixture-c'},catalog,'openai:fixture-a',null),'anthropic:fixture-c');assert.equal(RolequiltLiveClient.resolveModel({provider:'anthropic',modelId:''},catalog,'openai:fixture-a',null),'anthropic:fixture-b');assert.equal(RolequiltLiveClient.resolveModel({provider:'anthropic',modelId:''},catalog,'anthropic:fixture-c',null),'anthropic:fixture-c');assert.equal(RolequiltLiveClient.resolveModel({provider:'none',modelId:''},catalog,'anthropic:fixture-c',null),'anthropic:fixture-c');assert.throws(()=>RolequiltLiveClient.resolveModel({provider:'openai',modelId:'fixture-b'},catalog,'x',null),/unavailable/);assert.throws(()=>RolequiltLiveClient.resolveModel({provider:'google',modelId:''},catalog,'x',null),/not connected/);});
