
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');const core=require('../src/core.js'),demo=require('../src/demo-config.js');
test('provider choices are bounded inert preferences, no credentials or endpoint values',()=>{for(const provider of ['openai','anthropic','google','xai'])assert.deepEqual(core.validateModelPreference({provider,modelId:'sample-model'}),{provider,modelId:'sample-model'});for(const value of [{provider:'other',modelId:''},{provider:'none',modelId:'sample'},{provider:'openai',modelId:'https://example.invalid'},{provider:'openai',modelId:'x'.repeat(121)},{provider:'openai',modelId:'<script>'},{provider:'openai',modelId:'sample',credential:'demo'}])assert.throws(()=>core.validateModelPreference(value));});
test('preferences remain per-role/per-team and survive local state reload; invalid settings ignored',()=>{const state=core.seedState(demo),role=demo.roles[0].id,other=demo.roles[1].id;core.setModelPreference(state,demo,role,{provider:'openai',modelId:'sample-model'});assert.equal(state.modelPreferences[other].provider,'none');const restored=core.restoreState(JSON.stringify(state),demo);assert.equal(restored.state.modelPreferences[role].modelId,'sample-model');assert.equal(core.seedState(demo).modelPreferences[role].provider,'none');state.modelPreferences[role]={provider:'bad',modelId:''};assert.equal(core.restoreState(JSON.stringify(state),demo).state.modelPreferences[role].provider,'none');assert.throws(()=>core.setModelPreference(state,demo,'missing',{provider:'none',modelId:''}));});
test('optional config preference is compatible and cannot turn into an executable connection',()=>{const config=JSON.parse(JSON.stringify(demo));config.roles[0].modelPreference={provider:'google',modelId:''};assert.equal(core.validateConfig(config).roles[0].modelPreference.provider,'google');assert.equal(core.seedState(config).modelPreferences[config.roles[0].id].provider,'google');assert.deepEqual(core.validateConfig(demo),demo);});
test('settings UI discloses disconnected status and contains no key/login/network mechanism',()=>{const html=fs.readFileSync('index.html','utf8'),app=fs.readFileSync('src/app.js','utf8');assert.match(html,/Disconnected · preferences only/);assert.match(html,/Never paste API keys or passwords/);assert.match(app,/model ID not verified/);assert.doesNotMatch(app,/\bfetch\s*\(|XMLHttpRequest|WebSocket|type='password'/);assert.match(app,/input.maxLength=120/);});

test('subscription-only guide disables unverified routes and has no API onboarding',()=>{const app=fs.readFileSync('src/app.js','utf8'),html=fs.readFileSync('index.html','utf8');assert.match(app,/developers.openai.com\/codex\/auth/);assert.match(app,/link.rel='noopener noreferrer'/);assert.match(app,/link.target='_blank'/);assert.match(app,/Local subscription usage only/);assert.match(app,/option.disabled=!core.LOCAL_RUNTIME_CANDIDATES.includes\(id\)/);assert.doesNotMatch(app,/platform.openai.com\/api-keys|platform.claude.com\/settings\/keys|fetch\(/);assert.match(html,/No API billing or paid fallback/);const state=core.seedState(demo);for(const provider of ['anthropic','google','xai'])assert.throws(()=>core.setModelPreference(state,demo,demo.roles[0].id,{provider,modelId:''}),/route not verified/);assert.deepEqual(core.LOCAL_RUNTIME_CANDIDATES,['none','openai']);});
