'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {execFileSync}=require('node:child_process');const {scanContent,auditRepository}=require('../scripts/check-publish.cjs');
const git=(root,...args)=>execFileSync('git',['-C',root,'-c','user.name=Demo Maintainer','-c','user.email=maintainer@example.invalid','-c','commit.gpgsign=false','-c','core.hooksPath=/dev/null',...args],{encoding:'utf8',stdio:['ignore','pipe','pipe']});
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'rolequilt-audit-'));git(root,'init','--template=','-b','main');fs.writeFileSync(path.join(root,'publish-files.json'),JSON.stringify(['publish-files.json','index.html']));fs.writeFileSync(path.join(root,'index.html'),'A fictional offline demo.');git(root,'add','publish-files.json','index.html');git(root,'commit','-m','Add fictional demo');return root;}
test('accepts a fresh exact-listed repository',()=>{const root=fixture();try{assert.deepEqual(auditRepository(root),[]);}finally{fs.rmSync(root,{recursive:true});}});
test('rejects ignored private files and file symlinks',()=>{const root=fixture();try{fs.mkdirSync(path.join(root,'.git/info'),{recursive:true});fs.writeFileSync(path.join(root,'.git/info/exclude'),'private.json\n');fs.writeFileSync(path.join(root,'private.json'),'private');assert.match(auditRepository(root).join('\n'),/not allowlisted/);fs.unlinkSync(path.join(root,'private.json'));fs.symlinkSync('/tmp',path.join(root,'index.html.link'));assert.match(auditRepository(root).join('\n'),/symlink/);}finally{fs.rmSync(root,{recursive:true});}});
test('rejects history-only disclosures even when latest files are clean',()=>{const root=fixture();try{fs.writeFileSync(path.join(root,'index.html'),'Local path: '+'/'+'Users'+'/someone/private');git(root,'add','index.html');git(root,'commit','-m','Bad example');fs.writeFileSync(path.join(root,'index.html'),'Clean again.');git(root,'add','index.html');git(root,'commit','-m','Clean example');assert.match(auditRepository(root).join('\n'),/history.*private path/);}finally{fs.rmSync(root,{recursive:true});}});
test('rejects token-shaped values, real email addresses, private keys and credential assignments',()=>{
 for(const sample of ['gh'+'p_'+'A'.repeat(36),'AK'+'IA'+'A'.repeat(16),'person'+'@'+'private.test','-----BEGIN '+'PRIVATE KEY-----','api'+'_key = "'+'x'.repeat(32)+'"'])assert.ok(scanContent(sample).length);
 assert.deepEqual(scanContent('Fictional role: Planner. Read the schema.'),[]);
});
test('accepts the Claude co-author noreply address but not other vendor addresses',()=>{const {scanContent}=require('../scripts/check-publish.cjs');assert.deepEqual(scanContent('Co-Authored-By: Claude <noreply@anthropic.com>'),[]);assert(scanContent('Contact person'+String.fromCharCode(64)+'anthropic.com').includes('non-example email'));});
