/* Coordinator is inert until explicit enable; caller owns the process factory. */
'use strict';
const {EventEmitter}=require('node:events'),path=require('node:path');const {approvalResponse}=require('./guards.cjs');
class Engine extends EventEmitter{
 constructor({workspace,roles,createTransport,confirmed=false,threadStore=null}){super();if(!path.isAbsolute(workspace))throw Error('Absolute workspace required');this.workspace=workspace;this.roles=new Map(roles.map(r=>[r.id,r]));this.createTransport=createTransport;this.confirmed=confirmed;this.threadStore=threadStore;this.status='disconnected';this.threads=new Map();this.approvals=new Map();this.patches=new Map();this.models=[];this.turn=null;this.busy=false;this.generation=0;}
 update(status,detail){this.status=status;this.emit('state',{status,detail});}
 snapshot(){return {status:this.status,models:this.models,roleId:this.turn?.roleId||null,turnId:this.turn?.turnId||null,approvals:[...this.approvals].map(([id,v])=>({id,method:v.method,params:v.params}))};}
 async checkAccount(){const result=await this.rpc.call('account/read',{refreshToken:false});if(result?.account?.type!=='chatgpt')throw Error('Existing ChatGPT subscription required');const usage=await this.rpc.call('account/rateLimits/read',{});if(usage?.ordinaryUsageAllowed!==true)throw Error('Included usage unavailable or unknown');}
 async enable(){if(!this.confirmed||this.status!=='disconnected')throw Error('Explicit activation confirmation required');this.update('connecting');try{this.rpc=this.createTransport();this.rpc.on('notification',m=>this.notification(m));this.rpc.on('request',m=>this.request(m));this.rpc.on('closed',()=>this.disconnect('Runtime disconnected'));await this.rpc.call('initialize',{clientInfo:{name:'rolequilt',version:'0.1.0'},capabilities:{experimentalApi:true}});this.rpc.notify('initialized',{});await this.checkAccount();let cursor=null,models=[],pages=0;do{if(++pages>20)throw Error('Model catalog overflow');const response=await this.rpc.call('model/list',{includeHidden:false,cursor});if(!Array.isArray(response?.data))throw Error('Invalid model catalog');models.push(...response.data);cursor=response.nextCursor||null;}while(cursor);this.models=models.filter(m=>typeof m.id==='string'&&typeof m.model==='string').map(m=>({id:m.id,model:m.model,displayName:typeof m.displayName==='string'?m.displayName:m.id,supportedEfforts:(m.supportedReasoningEfforts||[]).map(e=>e.reasoningEffort)}));if(!this.models.length)throw Error('No available models');if(this.status!=='connecting')throw Error('Activation interrupted');this.update('ready');}catch(error){this.disconnect('Activation failed');throw error;}}
 async start(roleId,text,modelId){if(this.status!=='ready'||this.busy)throw Error('Bridge busy or disconnected');const role=this.roles.get(roleId),model=this.models.find(m=>m.id===modelId);if(!role||!model||typeof text!=='string'||!text.trim()||text.length>16000)throw Error('Invalid turn');this.busy=true;const generation=this.generation;this.timing={requestStartAt:new Date().toISOString()};this.update('running');try{await this.checkAccount();if(generation!==this.generation)throw Error('Disconnected');let threadId=this.threads.get(roleId);if(!threadId){const saved=this.threadStore?.get(roleId);const method=saved?'thread/resume':'thread/start';const params={cwd:this.workspace,runtimeWorkspaceRoots:[this.workspace],model:model.model,modelProvider:'openai',allowProviderModelFallback:false,approvalPolicy:'on-request',approvalsReviewer:'user',sandbox:'read-only',ephemeral:!this.threadStore,environments:[],developerInstructions:role.instructions||''};if(saved){params.threadId=saved;delete params.ephemeral;}const result=await this.rpc.call(method,params);if(result?.approvalPolicy!=='on-request'||result?.approvalsReviewer!=='user'||result?.sandbox?.type!=='readOnly'||result?.cwd!==this.workspace||result?.modelProvider!=='openai'||result?.model!==model.model||typeof result?.thread?.id!=='string')throw Error('Runtime policy mismatch');threadId=result.thread.id;this.threads.set(roleId,threadId);this.threadStore?.set(roleId,threadId);}
 this.turn={roleId,threadId,turnId:null};const result=await this.rpc.call('turn/start',{threadId,cwd:this.workspace,runtimeWorkspaceRoots:[this.workspace],model:model.model,approvalPolicy:'on-request',approvalsReviewer:'user',sandboxPolicy:{type:'readOnly',networkAccess:false},environments:[],...(model.supportedEfforts.includes('low')?{effort:'low'}:{}),input:[{type:'text',text}]});if(generation!==this.generation)throw Error('Disconnected');if(typeof result?.turn?.id!=='string')throw Error('Invalid turn response');if(this.turn){this.turn.turnId=result.turn.id;}return result.turn.id;
 }catch(error){this.disconnect('Turn start failed');throw error;}}
 notification(message){const p=message.params||{};if(message.method==='account/updated'){if(this.status!=='connecting'&&p.authMode!=='chatgpt')this.disconnect('Account mode changed; reconnect required');return;}if(message.method==='account/rateLimits/updated'){this.emit('usage-update',{requiresRecheck:true});return;}if(!this.turn||p.threadId!==this.turn.threadId)return;if(message.method==='item/started'&&p.turnId===this.turn.turnId&&p.item?.type==='fileChange'&&typeof p.item.id==='string'&&Array.isArray(p.item.changes)&&p.item.changes.length<=100&&p.item.changes.every(c=>typeof c.path==='string'&&typeof c.diff==='string')&&JSON.stringify(p.item.changes).length<=200000)this.patches.set(p.item.id,p.item.changes);if(message.method==='turn/started'&&typeof p.turn?.id==='string')this.turn.turnId=p.turn.id;if(message.method==='item/agentMessage/delta'&&typeof p.delta==='string'){if(!this.timing.firstTokenAt)this.timing.firstTokenAt=new Date().toISOString();this.emit('delta',{roleId:this.turn.roleId,delta:p.delta});}if(message.method==='turn/completed'&&typeof p.turn?.id==='string'&&(p.turn?.id===this.turn.turnId||this.turn.turnId===null)){this.timing.doneAt=new Date().toISOString();this.emit('completed',{roleId:this.turn.roleId,status:p.turn.status,timing:{...this.timing,firstTokenLatencyMs:this.timing.firstTokenAt?Date.parse(this.timing.firstTokenAt)-Date.parse(this.timing.requestStartAt):null,totalLatencyMs:Date.parse(this.timing.doneAt)-Date.parse(this.timing.requestStartAt)}});clearTimeout(this.cancelTimer);clearTimeout(this.approvalTimer);this.approvalTimer=null;this.approvals.clear();this.patches.clear();this.turn=null;this.busy=false;this.update('ready');}}
 request(message){const p=message.params||{};if(!this.turn||p.threadId!==this.turn.threadId||p.turnId!==this.turn.turnId||!['item/commandExecution/requestApproval','item/fileChange/requestApproval'].includes(message.method)||this.approvals.size>=16){this.rpc.reject(message.id);this.disconnect('Unsupported or unmatched runtime request');return;}if(message.method==='item/fileChange/requestApproval'){const changes=this.patches.get(p.itemId);if(!changes?.length){this.rpc.respond(message.id,{decision:'cancel'});this.disconnect('Patch details unavailable; approval denied');return;}message={...message,params:{...p,changes}};}if(message.method==='item/commandExecution/requestApproval'&&(typeof p.command!=='string'||!p.command.trim()||typeof p.cwd!=='string')){this.rpc.respond(message.id,{decision:'cancel'});this.disconnect('Command details unavailable; approval denied');return;}const id=String(message.id);if(this.approvals.has(id)){this.disconnect('Duplicate approval request');return;}this.approvals.set(id,message);if(!this.approvalTimer){this.approvalTimer=setTimeout(()=>this.disconnect('Approval timed out'),60000);this.approvalTimer.unref();}this.update('awaiting-approval');this.emit('approval',{id,method:message.method,params:message.params});}
 approve(id,decision){const message=this.approvals.get(id);if(!message)throw Error('Approval expired');const response=approvalResponse(message.method,decision);this.rpc.respond(message.id,response);this.approvals.delete(id);if(!this.approvals.size){clearTimeout(this.cancelTimer);clearTimeout(this.approvalTimer);this.approvalTimer=null;}this.update(this.approvals.size?'awaiting-approval':'running');if(decision==='cancel')return this.cancel();}
 async cancel(){if(!this.turn?.turnId){this.disconnect('Cancelled');return;}this.update('cancelling');this.cancelTimer=setTimeout(()=>this.disconnect('Cancellation acknowledgement timed out'),15000);this.cancelTimer.unref();try{await this.rpc.call('turn/interrupt',{threadId:this.turn.threadId,turnId:this.turn.turnId});}catch{this.disconnect('Cancellation failed');}}
 disconnect(reason='Disconnected'){if(this.status==='disconnected')return;this.generation++;for(const m of this.approvals.values()){try{this.rpc.respond(m.id,{decision:'cancel'});}catch{}}clearTimeout(this.cancelTimer);clearTimeout(this.approvalTimer);this.approvalTimer=null;this.approvals.clear();this.patches.clear();this.turn=null;this.busy=false;this.threads.clear();this.models=[];this.update('disconnected',reason);this.rpc?.close();}
}
module.exports={Engine};
