/* Shared live request handler; never generates a mock reply. */
'use strict';
class RolequiltLiveClient{
 static resolveModel(preference,models,fallback){if(preference?.provider==='openai'&&preference.modelId){const match=models.find(m=>m.id===preference.modelId||m.model===preference.modelId);if(!match)throw Error('Saved model is unavailable on this account. Choose a discovered model or clear that preference.');return match.id;}return fallback;}
 constructor(fetcher){this.fetcher=(...args)=>Reflect.apply(fetcher,globalThis,args);this.session=null;this.pending=false;this.after=0;}
 async post(route,data){const response=await this.fetcher(route,{method:'POST',headers:{'Content-Type':'application/json',...(this.session?{'X-Rolequilt-Session':this.session}:{})},body:JSON.stringify(data)});const result=await response.json();if(!response.ok){if(response.status===403){this.session=null;this.pending=false;this.after=0;}const error=Error(result.error||'Live request failed');error.status=response.status;throw error;}return result;}
 async pair(){const result=await this.post('/session',{});this.session=result.session;return result;}
 action(action,fields={}){if(!this.session)return Promise.reject(Error('Pair before live use'));return this.post('/action',{action,after:this.after,...fields});}
 async consult(roleId,recipientId,text,modelId,recipientModelId){if(this.pending)throw Error('A live turn is already pending');this.pending=true;try{return await this.action('consult',{roleId,recipientId,text,modelId,recipientModelId});}catch(error){this.pending=false;throw error;}}
 async send(roleId,text,modelId){if(this.pending)throw Error('A live turn is already pending');this.pending=true;try{return await this.action('start',{roleId,text,modelId});}catch(error){this.pending=false;throw error;}}
}
if(typeof module!=='undefined')module.exports={RolequiltLiveClient};
if(typeof document!=='undefined')(()=>{
 const client=new RolequiltLiveClient(fetch),chat=window.RolequiltChat;if(!chat)return;
 const node=(tag,text)=>{const e=document.createElement(tag);if(text)e.textContent=text;return e;},panel=node('section'),status=node('p','Not paired · pair and connect this selected team to chat.'),pair=node('button','Pair and connect this team'),enable=node('button','Connect local Codex'),mode=node('select'),model=node('select'),cancel=node('button','Cancel live turn'),approvals=node('div'),recipient=node('select'),consult=node('button','Consult selected teammate'),consultStatus=node('pre');recipient.setAttribute('aria-label','Consultation recipient');consultStatus.setAttribute('role','status');
 for(const [value,text]of [['live','Live Codex'],['demo','Explicit demo mode']]){const o=node('option',text);o.value=value;mode.append(o);}enable.disabled=true;cancel.disabled=true;panel.className='live-connection';status.setAttribute('role','status');panel.append(status,pair,enable,mode,model,recipient,consult,cancel,consultStatus,approvals);document.querySelector('#main-content').prepend(panel);
 let after=0,timer=null,stream=null,connected=false,polling=false,busySetup=false;
 function publish(value){value={...value,mode:mode.value};window.RolequiltLiveState=value;document.dispatchEvent(new CustomEvent('rolequilt-runtime',{detail:value}));}
 function render(data){publish({paired:!!client.session,teamKey:data.teamKey,status:data.status,models:data.models,roleModels:data.roleModels||{}});connected=['ready','running','awaiting-approval','cancelling'].includes(data.status);status.textContent='Codex '+data.status+' · '+(model.selectedOptions[0]?.textContent||'model not discovered');enable.disabled=!client.session||data.status!=='disconnected';pair.disabled=busySetup||client.pending;cancel.disabled=!['running','awaiting-approval'].includes(data.status);consult.disabled=mode.value!=='live'||data.status!=='ready'||!!data.consultation||client.pending;const previous=recipient.value;recipient.replaceChildren();for(const r of chat.config().roles){if(r.id===chat.role())continue;const o=node('option',r.name||r.id);o.value=r.id;recipient.append(o);}if([...recipient.options].some(o=>o.value===previous))recipient.value=previous;consult.disabled ||= !recipient.options.length;if(!connected)model.replaceChildren();if(data.models.length&&model.options.length===0)for(const m of data.models){const option=node('option',m.displayName);option.value=m.id;model.append(option);}
 approvals.replaceChildren();for(const a of data.approvals){const section=node('section'),details=node('pre',JSON.stringify(a.params,null,2));section.append(node('strong',a.method),details);for(const [decision,label]of [['accept','Allow once'],['decline','Deny'],['cancel','Deny and cancel']]){const b=node('button',label);b.onclick=()=>run(async()=>render(await client.action('approve',{id:a.id,decision})));section.append(b);}approvals.append(section);}
 for(const event of data.events||[]){if(event.revision<=after)continue;if(event.type==='delta'){if(!stream)stream={roleId:event.data.roleId,text:'',time:Date.now()};if(stream.roleId!==event.data.roleId)throw Error('Role stream mismatch');stream.text+=event.data.delta;chat.streamed(stream.roleId,stream.text,stream.time);}if(event.type==='completed'){if(event.data.status!=='completed'&&stream)chat.streamed(stream.roleId,stream.text+'\n[Turn '+event.data.status+']',stream.time);chat.complete();stream=null;client.pending=!!data.consultation;}if(event.type==='consultation'){const c=event.data;consultStatus.textContent=c.sourceId+' → '+c.recipientId+' · '+c.stage+'\nRequest: '+(c.request||'')+(c.reply?'\nReply: '+c.reply:'');if(c.type==='request')chat.user(c.roleId,c.text,c.time);if(c.type==='finished')client.pending=false;}}after=Math.max(after,data.revision||0);client.after=after;if(data.status==='disconnected'){client.pending=false;connected=false;status.textContent='Codex disconnected. No mock reply generated.';}}
 async function run(fn){try{await fn();}catch(error){connected=false;client.pending=false;clearInterval(timer);pair.disabled=false;enable.disabled=!client.session;status.textContent='Live error: '+error.message+' · click Pair and connect this team to recover.';publish({...window.RolequiltLiveState,paired:!!client.session,status:'disconnected',error:error.message});}}
 async function configureSelected(){return client.action('configure',{bundle:chat.bundle()});}
 async function poll(){if(polling)return;polling=true;try{await run(async()=>render(await client.action('state')));}finally{polling=false;}}
 function watch(){clearInterval(timer);timer=setInterval(poll,350);}
 pair.onclick=()=>run(async()=>{if(busySetup) return;busySetup=true;mode.value='live';pair.disabled=true;try{const result=await client.pair();after=0;client.after=0;stream=null;if(result.bundle?.length&&chat.isDemoTeam())chat.applyBundle(result.bundle);if(result.messages?.length)chat.restoreLive(result.messages,result.defaultTeamKey);await configureSelected();render(await client.action('enable'));watch();}finally{busySetup=false;pair.disabled=false;}});
 mode.onchange=()=>{publish({...window.RolequiltLiveState});status.textContent=mode.value==='demo'?'Explicit demo mode · no model requests':'Live mode · '+(window.RolequiltLiveState.status||'disconnected');};
 enable.onclick=()=>run(async()=>{mode.value='live';await configureSelected();render(await client.action('enable'));watch();});cancel.onclick=()=>run(async()=>render(await client.action('cancel')));
 document.querySelector('#composer').addEventListener('submit',event=>{if(mode.value==='demo')return;event.preventDefault();event.stopImmediatePropagation();run(async()=>{if(!connected)throw Error('Connect local Codex before sending');const roleId=chat.role(),input=document.querySelector('#message-input'),text=input.value;if(!text.trim())return;if(window.RolequiltLiveState?.teamKey!==RolequiltCore.storageKey(chat.config()))render(await configureSelected());const selected=RolequiltLiveClient.resolveModel(chat.preference(roleId),window.RolequiltLiveState?.models||[],model.value);const result=await client.send(roleId,text,selected);chat.user(roleId,text,result.userTime);render(result);});},true);
 consult.onclick=()=>run(async()=>{if(!connected||mode.value!=='live')throw Error('Connect live Codex before consultation');const input=document.querySelector('#message-input'),text=input.value,roleId=chat.role(),recipientId=recipient.value;if(!text.trim())throw Error('Write the consultation request in the message box first');if(window.RolequiltLiveState?.teamKey!==RolequiltCore.storageKey(chat.config()))render(await configureSelected());const models=window.RolequiltLiveState.models||[],selected=RolequiltLiveClient.resolveModel(chat.preference(roleId),models,model.value),recipientModel=RolequiltLiveClient.resolveModel(chat.preference(recipientId),models,model.value);const result=await client.consult(roleId,recipientId,text,selected,recipientModel);input.value='';render(result);});
 window.RolequiltLiveControls={connect(){if(!client.session)pair.onclick();else enable.onclick();}};publish({paired:false,status:'disconnected',models:[],roleModels:{}});
 window.addEventListener('pagehide',()=>clearInterval(timer));
})();
