/* Shared live request handler; never generates a mock reply. */
'use strict';
class RolequiltLiveClient{
 // Only call for a newly submitted user composer value. Never parse model output or imported prompts.
 static consultationIntent(text,roles,sourceId){
  if(typeof text!=='string'||!Array.isArray(roles))return {type:'chat'};
  const normalize=value=>String(value).normalize('NFKC').trim().replace(/\s+/g,' ').toLocaleLowerCase('en-US');
  const escape=value=>value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
  let input=normalize(text);const source=roles.find(r=>r.id===sourceId);
  // An optional address must name the currently selected role exactly.
  for(const alias of [source?.name,source?.id].filter(Boolean).map(normalize)){if(input.startsWith(alias+',')){input=input.slice(alias.length+1).trim();break;}}
  input=input.replace(/^(?:please\s+)?(?:(?:can|could|would|will) you\s+|i(?:'d| would) like you to\s+)?(?:please\s+)?/,'');
  const command=/^(?:consult|ask|talk (?:to|with)|speak (?:to|with)|check with|get (?:input|advice|feedback) from)\s+(.+)$/u.exec(input);
  if(!command)return {type:'chat'};
  const tail=command[1],matches=[];if(/^(?:me|us|yourself|what|why|how|when|where|whether)(?=$|\s)/u.test(tail))return {type:'chat'};
  for(const role of roles){const aliases=[role.name,role.id].filter(Boolean).map(normalize);if(aliases.some(alias=>new RegExp('^'+escape(alias)+'(?=$|[^\\p{L}\\p{N}_-])','u').test(tail)))matches.push(role);}
  if(matches.length!==1||matches[0].id===sourceId)return {type:'clarify'};
  // Multiple named roles or another delegation command require an explicit choice.
  const candidate=matches[0];
  for(const role of roles){if(role.id===candidate.id)continue;for(const alias of [role.name,role.id].filter(Boolean).map(normalize)){if(new RegExp('(?:^|[^\\p{L}\\p{N}_-])'+escape(alias)+'(?=$|[^\\p{L}\\p{N}_-])','u').test(tail))return {type:'clarify'};}}
  const head=[candidate.name,candidate.id].filter(Boolean).map(normalize).find(alias=>new RegExp('^'+escape(alias)+'(?=$|[^\\p{L}\\p{N}_-])','u').test(tail));
  if(/^(?:\s*(?:and|or|&|\/)|\s*,\s*[^:])/u.test(tail.slice(head.length))||/\b(?:consult|talk (?:to|with)|speak (?:to|with)|check with|ask)\s+/u.test(tail.slice(head.length)))return {type:'clarify'};
  return {type:'consult',recipientId:candidate.id};
 }
 static consultationMessages(c,roles=[]){
  const name=id=>roles.find(r=>r.id===id)?.name||id,time=c.time||Date.now(),base={roleId:c.sourceId,teamKey:c.teamKey,time},messages=[];
  if((c.type==='reply'||c.type==='finished')&&c.reply)messages.push({...base,type:'live',speakerId:c.recipientId,messageId:c.id+':reply',text:c.reply,partial:c.type==='finished'&&c.phase==='request'&&c.stage!=='completed'});
  let text=c.stage==='response'?name(c.recipientId)+' replied. Waiting for '+name(c.sourceId)+' to follow up.':'Asking '+name(c.recipientId)+'…';
  if(c.type==='finished')text=c.stage==='completed'?'Consultation complete.':(c.stage==='cancelled'?'Consultation cancelled.':'Consultation stopped: '+(c.reason||c.stage)+'.')+(c.reply?' The received '+name(c.recipientId)+' reply is kept above.':'')+(c.phase==='response'?' The follow-up did not complete.':'')+' No turns were retried.';
  messages.push({...base,type:'status',messageId:c.id+':progress',text});return messages;
 }
 // A role preference picks its runtime; blank model uses the picker choice when it belongs to that runtime, else that runtime's first model.
 static resolveModel(preference,models,fallback,runtime='openai'){const provider=preference?.provider;if(!provider||provider==='none')return fallback;const pool=models.filter(m=>(m.runtime||runtime)===provider);if(!pool.length)throw Error('Saved preference names a local runtime that is not connected. Choose Not chosen or connect that runtime.');if(preference.modelId){const match=pool.find(m=>m.id===preference.modelId||m.model===preference.modelId);if(!match)throw Error('Saved model is unavailable on this account. Choose a discovered model or clear that preference.');return match.id;}return pool.some(m=>m.id===fallback)?fallback:pool[0].id;}
 constructor(fetcher){this.fetcher=(...args)=>Reflect.apply(fetcher,globalThis,args);this.session=null;this.pending=false;this.after=0;this.generation=0;}
 async post(route,data){const generation=this.generation;const response=await this.fetcher(route,{method:'POST',headers:{'Content-Type':'application/json',...(this.session?{'X-Rolequilt-Session':this.session}:{})},body:JSON.stringify(data)});const result=await response.json();if(generation!==this.generation){const error=Error('Replaced session response ignored');error.stale=true;throw error;}if(!response.ok){if(response.status===403){this.session=null;this.pending=false;this.after=0;this.generation=0;}const error=Error(result.error||'Live request failed');error.status=response.status;throw error;}return result;}
 async pair(){this.generation++;this.session=null;this.pending=false;this.after=0;const result=await this.post('/session',{});this.session=result.session;return result;}
 action(action,fields={}){if(!this.session)return Promise.reject(Error('Pair before live use'));return this.post('/action',{action,after:this.after,...fields});}
 async consult(roleId,recipientId,text,modelId,recipientModelId){if(this.pending)throw Error('A live turn is already pending');this.pending=true;try{return await this.action('consult',{roleId,recipientId,text,modelId,recipientModelId});}catch(error){if(!error.stale)this.pending=false;throw error;}}
 async send(roleId,text,modelId){if(this.pending)throw Error('A live turn is already pending');this.pending=true;try{return await this.action('start',{roleId,text,modelId});}catch(error){if(!error.stale)this.pending=false;throw error;}}
}
if(typeof module!=='undefined')module.exports={RolequiltLiveClient};
if(typeof document!=='undefined')(()=>{
 const client=new RolequiltLiveClient(fetch),chat=window.RolequiltChat;if(!chat)return;
 const node=(tag,text)=>{const e=document.createElement(tag);if(text)e.textContent=text;return e;},panel=node('section'),status=node('p','Not paired · pair and connect this selected team to chat.'),pair=node('button','Pair and connect this team'),enable=node('button','Connect local runtime'),mode=node('select'),model=node('select'),cancel=node('button','Cancel live turn'),approvals=node('div'),recipient=node('select'),consult=node('button','Consult selected teammate'),consultStatus=node('p');recipient.setAttribute('aria-label','Consultation recipient');consultStatus.setAttribute('role','status');
 for(const [value,text]of [['live','Live local runtime'],['demo','Explicit demo mode']]){const o=node('option',text);o.value=value;mode.append(o);}enable.disabled=true;cancel.disabled=true;panel.className='live-connection';status.setAttribute('role','status');panel.append(status,pair,enable,mode,model,recipient,consult,cancel,consultStatus,approvals);document.querySelector('#main-content').prepend(panel);
 let after=0,timer=null,stream=null,connected=false,polling=false,busySetup=false,clarificationPending=false;
 function publish(value){value={...value,mode:mode.value};window.RolequiltLiveState=value;document.dispatchEvent(new CustomEvent('rolequilt-runtime',{detail:value}));}
 function render(data){publish({paired:!!client.session,runtime:data.runtime||null,teamKey:data.teamKey,status:data.status,models:data.models,roleModels:data.roleModels||{},runtime:data.runtime||null});connected=['ready','running','awaiting-approval','cancelling'].includes(data.status);const failed=(data.runtimes||[]).filter(r=>r.error).map(r=>r.label+' unavailable: '+r.error).join(' · ');status.textContent=(data.runtime?.label||'Runtime')+' '+data.status+' · '+(model.selectedOptions[0]?.textContent||'model not discovered')+(failed?' · '+failed:'');enable.disabled=!client.session||data.status!=='disconnected';pair.disabled=busySetup||client.pending;cancel.disabled=!['running','awaiting-approval'].includes(data.status);consult.disabled=mode.value!=='live'||data.status!=='ready'||!!data.consultation||client.pending;const previous=recipient.value;recipient.replaceChildren();if(clarificationPending){const o=node('option','Choose a teammate to consult');o.value='';recipient.append(o);}for(const r of chat.config().roles){if(r.id===chat.role())continue;const o=node('option',r.name||r.id);o.value=r.id;recipient.append(o);}if([...recipient.options].some(o=>o.value===previous))recipient.value=previous;consult.disabled ||= !recipient.options.length||!recipient.value;if(!connected)model.replaceChildren();if(data.models.length&&model.options.length===0)for(const m of data.models){const option=node('option',m.displayName);option.value=m.id;model.append(option);}
 approvals.replaceChildren();for(const a of data.approvals){const section=node('section'),details=node('pre',JSON.stringify(a.params,null,2));section.append(node('strong',a.method),details);for(const [decision,label]of [['accept','Allow once'],['decline','Deny'],['cancel','Deny and cancel']]){const b=node('button',label);b.onclick=()=>run(async()=>render(await client.action('approve',{id:a.id,decision})));section.append(b);}approvals.append(section);}
 for(const event of data.events||[]){if(event.revision<=after)continue;if(event.type==='delta'){if(event.data.teamKey&&event.data.teamKey!==RolequiltCore.storageKey(chat.config())){stream=null;continue;}if(!stream)stream={roleId:event.data.roleId,text:'',time:Date.now()};if(stream.roleId!==event.data.roleId)throw Error('Role stream mismatch');stream.text+=event.data.delta;chat.streamed(stream.roleId,stream.text,stream.time,event.data.relayId?{messageId:event.data.relayId+':'+stream.roleId}:{});}if(event.type==='completed'){if(event.data.status!=='completed'&&stream)chat.streamed(stream.roleId,stream.text+'\n[Turn '+event.data.status+']',stream.time);chat.complete();stream=null;client.pending=!!data.consultation;}if(event.type==='relay-message')chat.relayMessage(event.data);if(event.type==='consultation'){const c=event.data;consultStatus.textContent='Consultation '+c.stage+' · see the conversation below.';if(c.type==='finished')client.pending=false;}}after=Math.max(after,data.revision||0);client.after=after;pair.disabled=busySetup||client.pending;if(data.status==='disconnected'){client.pending=false;pair.disabled=busySetup;connected=false;if(stream){chat.streamed(stream.roleId,stream.text+'\n[Connection stopped; received text retained.]',stream.time);chat.complete();stream=null;}status.textContent='Runtime disconnected. Received replies are retained; reconnect to continue. No mock reply generated.';}}
 async function run(fn){try{await fn();}catch(error){if(error.stale)return;connected=false;client.pending=false;clearInterval(timer);pair.disabled=false;enable.disabled=!client.session;status.textContent='Live error: '+error.message+' · click Pair and connect this team to recover.';publish({...window.RolequiltLiveState,paired:!!client.session,status:'disconnected',error:error.message});}}
 async function configureSelected(){return client.action('configure',{bundle:chat.bundle()});}
 async function poll(){if(polling)return;polling=true;try{await run(async()=>render(await client.action('state')));}finally{polling=false;}}
 function watch(){clearInterval(timer);timer=setInterval(poll,350);}
 pair.onclick=()=>run(async()=>{if(busySetup) return;busySetup=true;clearInterval(timer);connected=false;mode.value='live';publish({paired:false,status:'connecting',models:[],roleModels:{}});pair.disabled=true;try{const result=await client.pair();after=0;client.after=0;stream=null;if(result.bundle?.length&&chat.isDemoTeam())chat.applyBundle(result.bundle);if(result.messages?.length)chat.restoreLive(result.messages,result.defaultTeamKey);await configureSelected();render(await client.action('enable'));watch();}finally{busySetup=false;clarificationPending=false;pair.disabled=false;}});
 mode.onchange=()=>{publish({...window.RolequiltLiveState});status.textContent=mode.value==='demo'?'Explicit demo mode · no model requests':'Live mode · '+(window.RolequiltLiveState.status||'disconnected');};
 enable.onclick=()=>run(async()=>{mode.value='live';await configureSelected();render(await client.action('enable'));watch();});cancel.onclick=()=>run(async()=>render(await client.action('cancel')));
 document.querySelector('#composer').addEventListener('submit',event=>{if(mode.value==='demo')return;event.preventDefault();event.stopImmediatePropagation();run(async()=>{if(busySetup)return;if(!connected)throw Error('Connect local runtime before sending');const roleId=chat.role(),input=document.querySelector('#message-input'),text=input.value;if(!text.trim())return;const intent=RolequiltLiveClient.consultationIntent(text,chat.config().roles,roleId);if(intent.type==='clarify'){clarificationPending=true;recipient.value='';consultStatus.textContent='Which teammate should receive this request? Choose a teammate above, then click Consult selected teammate. Nothing has been sent.';return;}clarificationPending=false;if(window.RolequiltLiveState?.teamKey!==RolequiltCore.storageKey(chat.config()))render(await configureSelected());const selected=RolequiltLiveClient.resolveModel(chat.preference(roleId),window.RolequiltLiveState?.models||[],model.value,window.RolequiltLiveState?.runtime?.id);if(intent.type==='consult'){const recipientModel=RolequiltLiveClient.resolveModel(chat.preference(intent.recipientId),window.RolequiltLiveState?.models||[],model.value,window.RolequiltLiveState?.runtime?.id);const result=await client.consult(roleId,intent.recipientId,text,selected,recipientModel);chat.user(roleId,text,result.userTime);render(result);}else{const result=await client.send(roleId,text,selected);chat.user(roleId,text,result.userTime);render(result);}});},true);
 consult.onclick=()=>run(async()=>{if(!connected||mode.value!=='live')throw Error('Connect the local runtime before consultation');const input=document.querySelector('#message-input'),text=input.value,roleId=chat.role(),recipientId=recipient.value;if(!text.trim())throw Error('Write the consultation request in the message box first');if(!recipientId){consultStatus.textContent='Choose a teammate before consultation. Nothing has been sent.';return;}clarificationPending=false;if(window.RolequiltLiveState?.teamKey!==RolequiltCore.storageKey(chat.config()))render(await configureSelected());const models=window.RolequiltLiveState.models||[],selected=RolequiltLiveClient.resolveModel(chat.preference(roleId),models,model.value,window.RolequiltLiveState.runtime?.id),recipientModel=RolequiltLiveClient.resolveModel(chat.preference(recipientId),models,model.value,window.RolequiltLiveState.runtime?.id);const result=await client.consult(roleId,recipientId,text,selected,recipientModel);chat.user(roleId,text,result.userTime);render(result);});
 recipient.onchange=()=>{consult.disabled=mode.value!=='live'||window.RolequiltLiveState?.status!=='ready'||client.pending||!recipient.value;};
 window.RolequiltLiveControls={connect(){if(!client.session)pair.onclick();else enable.onclick();}};publish({paired:false,status:'disconnected',models:[],roleModels:{}});
 window.addEventListener('pagehide',()=>clearInterval(timer));
})();
