/* Explicitly constructed loopback server; not wired to npm start. */
'use strict';
const http=require('node:http'),fs=require('node:fs'),path=require('node:path');const {createGuard}=require('./guards.cjs');
function createBridgeServer({engine,port,roles,persistMessage=()=>{},app=false,bundle=[],loadMessages=()=>[]}){
 const core=require('../src/core.js');const defaultTeamKey=bundle.length?core.storageKey(core.validateBundle(bundle).config):null;const messages=loadMessages();const record=m=>{persistMessage(m);messages.push(m);if(messages.length>300)messages.shift();};let guard=createGuard(port);let heartbeat=null,events=[],revision=0;const replies=new Map();engine.on('delta',e=>{replies.set(e.roleId,(replies.get(e.roleId)||'')+e.delta);if(replies.get(e.roleId).length>200000)engine.disconnect('Reply too large');});engine.on('completed',e=>{const text=replies.get(e.roleId)||'';replies.delete(e.roleId);if(e.status==='completed'&&text){try{record({roleId:e.roleId,teamKey:e.teamKey,type:'live',text,time:Date.now(),timing:e.timing});}catch{engine.disconnect('Reply persistence failed');}}});
 for(const type of ['state','delta','approval','completed'])engine.on(type,data=>{events.push({revision:++revision,type,data});if(events.length>256||Buffer.byteLength(JSON.stringify(events))>1048576){events=[];engine.disconnect('Event buffer overflow');}});
 const server=http.createServer(async(req,res)=>{
  const headers={'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; script-src 'self'; connect-src 'self'; style-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'"};
  const reply=(status,value)=>{res.writeHead(status,{...headers,'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(value));};
  if(req.headers.host!=='127.0.0.1:'+port)return reply(403,{error:'Host rejected'});
  const assets=new Map([['/','index.html'],['/src/core.js','src/core.js'],['/src/demo-config.js','src/demo-config.js'],['/src/import-prompt.js','src/import-prompt.js'],['/src/provider-settings.js','src/provider-settings.js'],['/src/app.js','src/app.js'],['/src/styles.css','src/styles.css']]);
  if(req.method==='GET'&&app&&(assets.has(req.url)||req.url==='/bridge/live-ui.js')){const file=req.url==='/bridge/live-ui.js'?path.join(__dirname,'live-ui.js'):path.join(__dirname,'..',assets.get(req.url));if(fs.lstatSync(file).isSymbolicLink())return reply(404,{error:'Not found'});let body=fs.readFileSync(file,'utf8');if(req.url==='/')body=body.replace("connect-src 'none'","connect-src 'self'").replace('>OFFLINE DEMO</strong>','>LIVE WORKSPACE · NOT CONNECTED</strong>').replace('Local configuration & fixed previews · No live agents or external actions','Pair and connect this selected team to enable live chat').replace('</head>','<script defer src="/bridge/live-ui.js"></script></head>');res.writeHead(200,{...headers,'Content-Type':file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.css')?'text/css; charset=utf-8':'text/javascript; charset=utf-8'});return res.end(body);}
  if(req.method==='GET'&&!app&&['/','/ui.js'].includes(req.url)){const file=path.join(__dirname,req.url==='/'?'ui.html':'ui.js');res.writeHead(200,{...headers,'Content-Type':req.url==='/'?'text/html; charset=utf-8':'text/javascript; charset=utf-8'});return res.end(fs.readFileSync(file));}
  if(req.method!=='POST'||!['/session','/action'].includes(req.url))return reply(404,{error:'Not found'});
  if(req.headers['content-type']!=='application/json')return reply(415,{error:'JSON required'});
  try{if(req.url==='/action')guard.check(req.headers);else if(req.headers.origin!=='http://127.0.0.1:'+port||req.headers['sec-fetch-site']!=='same-origin')throw Error();}catch{return reply(403,{error:'Session rejected'});}
  let bytes=0,body='',userTime=null;try{for await(const chunk of req){bytes+=chunk.length;if(bytes>core.BUNDLE_BYTES*3){reply(413,{error:'Request too large'});req.destroy();return;}body+=chunk.toString('utf8');}const data=JSON.parse(body);if(!data||typeof data!=='object'||Array.isArray(data))throw Error();
   if(req.url==='/session'){engine.disconnect('Browser explicitly paired a new session');events=[];revision=0;replies.clear();guard.close();guard=createGuard(port);const session=guard.pair(req.headers);return reply(200,{session,roles:roles.map(r=>({id:r.id,name:r.name})),bundle,messages,defaultTeamKey});}
   clearTimeout(heartbeat);heartbeat=setTimeout(()=>{guard.close();engine.disconnect('Browser heartbeat lost');},15000);heartbeat.unref();
   if(data.action==='configure'){const reviewed=core.validateBundle(data.bundle);if(reviewed.missing.length)throw Error('Selected team bundle is incomplete');engine.configureTeam(reviewed.config,reviewed.files);}else if(data.action==='enable')await engine.enable();else if(data.action==='start'){await engine.start(data.roleId,data.text,data.modelId);userTime=Date.now();record({roleId:data.roleId,teamKey:engine.teamKey,type:'user',text:data.text,time:userTime});}else if(data.action==='approve')await engine.approve(data.id,data.decision);else if(data.action==='cancel')await engine.cancel();else if(data.action==='disconnect'){engine.disconnect();guard.close();}else if(data.action!=='state')return reply(400,{error:'Unknown action'});
   const after=Number.isInteger(data.after)?data.after:0;reply(200,{...engine.snapshot(),userTime,events:events.filter(e=>e.revision>after),revision});
  }catch{reply(400,{error:'Action failed; review disconnected/runtime state',status:engine.status});}
 });
 server.on('close',()=>{clearTimeout(heartbeat);guard.close();engine.disconnect('Bridge closed');});const listen=server.listen.bind(server);server.listen=callback=>listen(port,'127.0.0.1',callback);return server;
}
module.exports={createBridgeServer};
