'use strict';
(()=>{const $=id=>document.getElementById(id);let session=null,after=0,timer=null,output='';const element=(tag,text)=>{const n=document.createElement(tag);n.textContent=text;return n;};
async function call(action,fields={}){const response=await fetch('/action',{method:'POST',headers:{'Content-Type':'application/json','X-Rolequilt-Session':session},body:JSON.stringify({action,after,...fields})});const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed');render(data);return data;}
function render(data){$('status').textContent=data.status;$('send').disabled=data.status!=='ready';$('cancel').disabled=!['running','awaiting-approval','cancelling'].includes(data.status);$('enable').disabled=data.status!=='disconnected';const current=$('model').value;$('model').replaceChildren(...data.models.map(m=>{const n=element('option',m.displayName);n.value=m.id;return n;}));if([...$('model').options].some(m=>m.value===current))$('model').value=current;
 $('approvals').replaceChildren();for(const a of data.approvals){const section=element('section',''),details=element('pre',a.method+'\n'+JSON.stringify(a.params,null,2));section.append(details);for(const [decision,label]of [['accept','Allow once'],['decline','Deny'],['cancel','Deny and cancel turn']]){const b=element('button',label);b.onclick=()=>run(()=>call('approve',{id:a.id,decision}));section.append(b);}$('approvals').append(section);}
 for(const event of data.events){if(event.type==='delta')output+=event.data.delta;if(event.type==='completed')output+='\n[Turn '+event.data.status+']\n';}output=output.slice(-200000);$('output').textContent=output;after=data.revision;}
async function run(fn){try{await fn();}catch(error){$('status').textContent=error.message;}}
$('pair').onclick=()=>run(async()=>{const r=await fetch('/session',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(!r.ok)throw Error('Pairing rejected; restart bridge for a new session');const data=await r.json();session=data.session;$('role').replaceChildren(...data.roles.map(role=>{const n=element('option',role.name);n.value=role.id;return n;}));$('pair').disabled=true;$('enable').disabled=false;$('disconnect').disabled=false;await call('state');timer=setInterval(()=>run(()=>call('state')),2000);});
$('enable').onclick=()=>run(()=>call('enable'));$('send').onclick=()=>run(()=>call('start',{roleId:$('role').value,modelId:$('model').value,text:$('message').value}));$('cancel').onclick=()=>run(()=>call('cancel'));$('disconnect').onclick=()=>run(async()=>{await call('disconnect');clearInterval(timer);session=null;$('enable').disabled=true;$('disconnect').disabled=true;});window.addEventListener('pagehide',()=>{clearInterval(timer);});})();
