/* Render configuration and local state as DOM text. No HTML input, eval or network. */
'use strict';
(() => {
  const $=selector=>document.querySelector(selector);
  const node=(tag,cls,text)=>{const el=document.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el;};
  const paths={chat:'M4 4h16v11H8l-4 4z',board:'M3 4h18v16H3zM9 4v16M15 4v16',unplug:'M3 3l18 18M9 3v4m6-4v4M6 7h12v3a6 6 0 0 1-6 6v5M7 13a6 6 0 0 0 4 3',check:'m5 12 4 4L19 6',reset:'M3 10a9 9 0 1 1 1 8M3 4v6h6',info:'M12 11v6M12 7h.01M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',arrow:'M12 20V4m-6 6 6-6 6 6',spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5z',shield:'m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6zM8 12l3 3 5-6',orbit:'M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0M22 7c3 4-1 11-7 14S2 21 2 17 6 6 12 3 20 3 22 7',menu:'M4 6h16M4 12h16M4 18h16',close:'m6 6 12 12M6 18 18 6',handoff:'M4 8h15m-4-4 4 4-4 4M20 16H5m4-4-4 4 4 4'};
  const ns='http://www.w3.org/2000/svg';
  function svgPath(d,attrs={}){const p=document.createElementNS(ns,'path');p.setAttribute('d',d);for(const [k,v]of Object.entries(attrs))p.setAttribute(k,v);return p;}
  function icon(name){const svg=document.createElementNS(ns,'svg');svg.setAttribute('class','icon');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');svg.append(svgPath(paths[name]||paths.chat));return svg;}
  function avatar(role){
    const shapes=['M11 5C5 7 3 25 6 32s15 2 24-5S26 11 20 7 15 4 11 5Z','M10 6C3 9 1 25 8 32s20 3 25-5 0-17-6-21S17 3 10 6Z','M20 3C9 3 3 10 3 20s7 17 18 17 16-9 16-18S29 3 20 3Z','M12 4 30 7 38 23 27 36 10 34 3 19Z','M11 4h18a8 8 0 0 1 8 8v16a9 9 0 0 1-9 9H13A10 10 0 0 1 3 27V14A10 10 0 0 1 11 4Z'];
    const wrap=node('span','avatar');const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 40 40');svg.setAttribute('aria-hidden','true');svg.append(svgPath(shapes[role.shape],{fill:role.color}),svgPath('m15 15 2 5m8-5 2 5',{stroke:'#252629','stroke-width':'3.3','stroke-linecap':'round'}));wrap.append(svg);return wrap;
  }
  let config,registry,registryStorageOK=true;
  try{let raw=null;try{raw=localStorage.getItem(RolequiltCore.REGISTRY_KEY);}catch{registryStorageOK=false;}registry=RolequiltCore.createTeamRegistry(raw,RolequiltDemo);config=registry.current();}catch{
    $('#app').replaceChildren(node('div','error-panel','Demo configuration could not be loaded. Restore the fictional example and rebuild it. No connection was attempted.'));return;
  }
  const core=RolequiltCore,STATUS=core.STATUS;let key=registry.currentKey();
  let storageOK=true,loaded;
  try{loaded=core.restoreState(localStorage.getItem(key),config);}catch{storageOK=false;loaded={state:core.seedState(config),recovered:false};}
  let state=loaded.state,statusFilter='all',ownerFilter='all',toastTimer;
  const active=()=>config.roles.find(r=>r.id===state.agent);
  function storageLabel(){const persisted=storageOK&&registryStorageOK;const el=$('#storage-state');el.replaceChildren(icon(persisted?'check':'info'),node('span','',persisted?'Saved in this browser':'Session only · storage unavailable'));el.title=persisted?'Only browser storage is used. No server receives this data. Do not enter secrets.':'Changes remain in memory and may be lost when this page closes.';}
  function save(){try{localStorage.setItem(key,JSON.stringify(state));storageOK=true;}catch{storageOK=false;}storageLabel();}
  function toast(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,3500);}
  document.querySelectorAll('[data-icon]').forEach(el=>el.replaceChildren(icon(el.dataset.icon)));
  function renderConfig(){
    $('#role-count').textContent=String(config.roles.length).padStart(2,'0');$('#nav-task-count').textContent=config.tasks.length;
    $('#context-role-count').textContent=config.roles.length;$('#context-task-count').textContent=config.tasks.length;
    for(const f of ['label','heading','description'])$('#focus-'+f).textContent=config.team.focus[f];$('#team-tagline').textContent=config.team.tagline;
    $('#owner-filter').replaceChildren();const all=node('option','','Everyone');all.value='all';$('#owner-filter').append(all);
    for(const r of config.roles){const option=node('option','',r.name);option.value=r.id;$('#owner-filter').append(option);}
    $('#local-team-select').replaceChildren();for(const entry of registry.listEntries()){const option=node('option','',entry.config.team.name);option.value=entry.key;$('#local-team-select').append(option);}$('#local-team-select').value=key;
  }
  function activate(next){save();config=next;key=registry.currentKey();try{loaded=core.restoreState(localStorage.getItem(key),config);}catch{loaded={state:core.seedState(config),recovered:false};storageOK=false;}state=loaded.state;statusFilter='all';ownerFilter='all';renderConfig();render();closeDrawer();}
  function saveRegistry(){try{localStorage.setItem(core.REGISTRY_KEY,registry.serialize());registryStorageOK=true;storageLabel();}catch{registryStorageOK=false;storageLabel();toast('Team is active for this session; browser storage unavailable.');}}
  $('#local-team-select').onchange=()=>{activate(registry.select($('#local-team-select').value));saveRegistry();};
  $('#prepare-prompt').value=RolequiltImportPrompt;
  $('#prepare-copy').onclick=async()=>{try{if(!navigator.clipboard?.writeText)throw Error('Clipboard unavailable');await navigator.clipboard.writeText(RolequiltImportPrompt);$('#prepare-copy-status').textContent='Preparation prompt copied.';}catch{$('#prepare-prompt').focus();$('#prepare-prompt').select();$('#prepare-copy-status').textContent='Automatic copy unavailable. Prompt selected: press your system Copy shortcut, or select and copy the text manually.';}};
  let fileRevision=0;
  function cancelImport(){fileRevision++;registry.cancel();$('#import-file').value='';$('#import-folder').value='';$('#import-bundle-summary').replaceChildren();$('#import-preview').hidden=true;$('#import-apply').disabled=true;$('#import-error').textContent='';}
  $('#import-open').onclick=()=>{cancelImport();$('#import-dialog').showModal();};
  function clearPending(){registry.cancel();$('#import-preview').hidden=true;$('#import-apply').disabled=true;$('#import-error').textContent='';$('#import-bundle-summary').replaceChildren();}
  function previewImport(candidate,bundle=null){
    $('#import-team-name').textContent=candidate.team.name+' · '+candidate.roles.length+' roles';$('#import-roster').replaceChildren(...candidate.roles.map(r=>node('li','',r.name+' — '+r.label+' · '+r.specialty)));$('#import-fields').textContent=JSON.stringify(candidate,null,2);
    const summary=$('#import-bundle-summary');summary.replaceChildren();
    if(bundle){summary.append(node('p','',bundle.files.length+' files · '+bundle.totalBytes.toLocaleString()+' bytes · imported text only; no capabilities activated.'));
      const mapping=node('ul');for(const ref of bundle.mapping)mapping.append(node('li','',ref.roleName+' → '+ref.path+' · '+ref.kind+' · '+(bundle.missing.includes(ref.path)?'MISSING/EMPTY':'present')));summary.append(mapping);
      for(const file of bundle.files){const details=node('details'),title=node('summary','',file.path+' · '+new TextEncoder().encode(file.text).length+' bytes'),text=node('pre','import-text',file.text);details.append(title,text);summary.append(details);}
      if(bundle.missing.length)$('#import-error').textContent='Missing or empty required files: '+bundle.missing.join(', ');
    }
    $('#import-preview').hidden=false;$('#import-apply').disabled=Boolean(bundle?.missing.length);
  }
  $('#import-file').onchange=async()=>{const revision=++fileRevision;clearPending();$('#import-folder').value='';const file=$('#import-file').files[0];if(!file)return;
    try{if(file.size>core.CONFIG_BYTES)throw Error('File exceeds 64 KiB.');const text=new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer());if(revision!==fileRevision)return;previewImport(registry.prepare(text));}catch(error){if(revision!==fileRevision)return;$('#import-error').textContent=error instanceof TypeError?'File must be valid UTF-8 text.':error.message;}
  };
  $('#import-folder').onchange=async()=>{const revision=++fileRevision;clearPending();$('#import-file').value='';const files=[...$('#import-folder').files];if(!files.length)return;
    try{if(files.length>core.BUNDLE_FILES)throw Error('Folder exceeds 64 files.');let total=0,root=null;const entries=[];
      for(const file of files){const parts=(file.webkitRelativePath||'').split('/');if(parts.length<2)throw Error('Use folder selection to preserve relative file paths.');if(root===null)root=parts[0];if(parts[0]!==root)throw Error('Choose one folder root.');core.portablePath(root+'/notes.txt');const path=parts.slice(1).join('/');core.portablePath(path);const limit=path==='team-config.json'?core.CONFIG_BYTES:core.FILE_BYTES;if(file.size>limit)throw Error('A selected file exceeds its size limit.');total+=file.size;if(total>core.BUNDLE_BYTES)throw Error('Folder exceeds 1 MiB.');entries.push({path,file});}
      const decoded=[];for(const entry of entries){const text=new TextDecoder('utf-8',{fatal:true}).decode(await entry.file.arrayBuffer());if(revision!==fileRevision)return;decoded.push({path:entry.path,text});}
      const bundle=registry.prepareBundle(decoded);previewImport(bundle.config,bundle);
    }catch(error){if(revision!==fileRevision)return;$('#import-error').textContent=error instanceof TypeError?'Files must be valid UTF-8 text.':error.message;}
  };
  $('#import-cancel').onclick=()=>{cancelImport();$('#import-dialog').close();};
  $('#import-dialog').addEventListener('close',cancelImport);
  $('#import-apply').onclick=()=>{try{const next=registry.apply();activate(next);saveRegistry();$('#import-dialog').close();toast('Reviewed team applied locally. No upload or agent execution.');}catch(error){$('#import-error').textContent=error.message;}};
  renderConfig();
  function renderRoles(){
    const list=$('#agent-list');list.replaceChildren();
    for(const r of config.roles){
      const selected=r.id===state.agent&&state.view==='chat',button=node('button','agent-button'+(selected?' active':''));button.dataset.agent=r.id;button.setAttribute('aria-label',r.name+' — '+r.label);if(selected)button.setAttribute('aria-current','page');
      const meta=node('span','agent-meta'),name=node('span','agent-name',r.name);if(r.id===config.team.leadRoleId)name.append(node('small','','LEAD'));
      const last=state.messages[r.id].filter(m=>m.type==='user').at(-1);meta.append(name,node('span','agent-sub',r.label),node('span','agent-preview',last?'You: '+last.text:r.summary));button.append(avatar(r),meta);
      button.onclick=()=>{state.agent=r.id;state.view='chat';save();render();closeDrawer();$('#message-input').focus({preventScroll:true});};list.append(button);
    }
  }
  function messageHeader(role,who,chip,time){const top=node('div','message-top');if(who!=='You')top.append(avatar(role));top.append(node('b','',who),node('span','sample-chip',chip));if(time!==undefined){const t=node('time','',new Date(time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}));top.append(t);}return top;}
  function renderSample(role){
    const fragment=document.createDocumentFragment();fragment.append(node('div','sample-divider','CONFIGURED SAMPLE · ILLUSTRATIVE ONLY'));
    const user=node('article','message user');user.append(messageHeader(role,'You','Sample'),node('div','message-bubble','How could this '+role.label.toLowerCase()+' role help this configured team?'));fragment.append(user);
    const article=node('article','message agent'),content=node('div','agent-content'),bubble=node('div','message-bubble');article.append(messageHeader(role,role.name,'Sample'));bubble.append(node('h2','',role.heading),node('p','',role.intro));
    const card=node('div','priority-card'),eye=node('div','card-eyebrow','A POSSIBLE FIRST FOCUS');eye.prepend(icon('spark'));card.append(eye);
    role.focus.forEach((step,i)=>{const row=node('div','priority-step'),copy=node('div');copy.append(node('b','',step.title),node('span','',step.detail));row.append(node('div','step-num',String(i+1).padStart(2,'0')),copy);card.append(row);});
    bubble.append(card,node('div','message-note','Configured role description. No model is connected and no work is dispatched.'));const handoff=node('div','handoff-line','Illustrative workflow · no task dispatched');handoff.prepend(icon('handoff'));content.append(bubble,handoff);article.append(content);fragment.append(article);return fragment;
  }
  function renderMessage(message,role){const article=node('article','message '+(message.type==='user'?'user':'agent'));article.append(messageHeader(role,message.type==='user'?'You':role.name,message.type==='user'?'Local only':'Fixed preview · no AI',message.time));const body=node('div',message.type==='user'?'':'agent-content');body.append(node('div','message-bubble',message.text));article.append(body);return article;}
  function composer(){const length=$('#message-input').value.length;$('#send-button').disabled=!$('#message-input').value.trim();$('#char-count').textContent=length.toLocaleString()+' / 4,000';}
  function renderChat(){const role=active();$('#header-avatar').replaceChildren(avatar(role));$('#chat-title').textContent=role.name;$('#chat-subtitle').textContent=role.label+' · '+role.specialty;$('#details-open').setAttribute('aria-label','View '+role.name+' role details');$('#messages').setAttribute('aria-label',role.name+' demo conversation history');$('#messages-inner').replaceChildren(renderSample(role),...state.messages[role.id].map(m=>renderMessage(m,role)));$('#message-input').value=state.drafts[role.id];$('#message-input').placeholder='Message '+role.name+' locally…';$('label[for="message-input"]').textContent='Message '+role.name+' locally';$('#preview-toggle').checked=state.preview;
    $('#suggestions').replaceChildren();for(const prompt of role.prompts){const b=node('button','suggestion',prompt);b.prepend(node('span','','↗'));b.onclick=()=>{state.drafts[role.id]=prompt;$('#message-input').value=prompt;composer();save();$('#message-input').focus();};$('#suggestions').append(b);}composer();$('#messages').scrollTop=state.messages[role.id].length?$('#messages').scrollHeight:0;
  }
  function renderContext(){$('#context-tasks').replaceChildren();for(const task of state.tasks.slice(0,3)){const row=node('div','task-mini'),copy=node('div');copy.append(node('b','',task.title),node('span','',config.roles.find(r=>r.id===task.owner).name+' · '+STATUS[task.status]+' · Demo'));row.append(node('i','status-circle '+task.status),copy);$('#context-tasks').append(row);}}
  function renderBoard(){
    $('#stats').replaceChildren();for(const [label,status]of [['All tasks','all'],['In progress','progress'],['Blocked','blocked'],['Done','done']]){const stat=node('div','stat'),heading=node('span','stat-label',label);heading.prepend(node('i','status-circle '+(status==='all'?'':status)));stat.append(heading,node('strong','',String(status==='all'?state.tasks.length:state.tasks.filter(t=>t.status===status).length)));$('#stats').append(stat);}
    $('#status-filters').replaceChildren();for(const [status,label]of Object.entries({all:'All tasks',...STATUS})){const b=node('button','filter'+(statusFilter===status?' active':''),label);b.dataset.filter=status;b.setAttribute('aria-pressed',String(statusFilter===status));b.onclick=()=>{statusFilter=status;renderBoard();$('[data-filter="'+status+'"]').focus();};$('#status-filters').append(b);}
    const rows=$('#task-rows');rows.replaceChildren();const filtered=state.tasks.filter(t=>(statusFilter==='all'||t.status===statusFilter)&&(ownerFilter==='all'||t.owner===ownerFilter));if(!filtered.length){rows.append(node('p','board-empty','No demo tasks match these filters. Choose another owner or status.'));return;}
    for(const task of filtered){const role=config.roles.find(r=>r.id===task.owner),row=node('article','task-row'),main=node('div','task-main'),owner=node('div','task-owner',role.name),status=node('div','task-status'),label=node('label','','Local preview only'),select=node('select');row.dataset.task=task.id;main.append(node('div','task-id',task.id+' / DEMO'),node('h2','task-title',task.title),node('div','task-description',task.description));owner.prepend(avatar(role));select.id='status-'+task.id;label.htmlFor=select.id;select.setAttribute('aria-label','Demo status for '+task.title);for(const [id,text]of Object.entries(STATUS)){const option=node('option','',text);option.value=id;select.append(option);}select.value=task.status;
      select.onchange=()=>{task.status=select.value;save();renderBoard();renderContext();toast('Demo status saved locally. No work dispatched.');($('#status-'+task.id)||$('#owner-filter')).focus();};status.append(label,select);row.append(main,owner,status);rows.append(row);}
  }
  function render(){renderRoles();$('#chat-view').hidden=state.view!=='chat';$('#board-view').hidden=state.view!=='board';for(const view of ['chat','board']){const button=$(view==='chat'?'#nav-chats':'#nav-board');button.classList.toggle('active',state.view===view);if(state.view===view)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current');}$('#breadcrumb-current').textContent=state.view==='board'?'Shared task board':config.team.name;if(state.view==='board')renderBoard();else renderChat();renderContext();storageLabel();}
  function setView(view){state.view=view;save();render();closeDrawer();$(view==='board'?'#board-title':'#message-input').focus({preventScroll:true});}
  $('#nav-chats').onclick=()=>setView('chat');$('#nav-board').onclick=$('#context-board').onclick=()=>setView('board');
  $('#owner-filter').onchange=()=>{ownerFilter=$('#owner-filter').value;renderBoard();};
  $('#message-input').oninput=()=>{state.drafts[state.agent]=$('#message-input').value.slice(0,4000);composer();save();};
  $('#message-input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing&&e.keyCode!==229){e.preventDefault();$('#composer').requestSubmit();}};
  $('#composer').onsubmit=e=>{e.preventDefault();if(!$('#message-input').value.trim())return;try{core.appendLocalMessage(state,config,state.agent,$('#message-input').value,state.preview);}catch{toast('Use a message between 1 and 4,000 characters.');return;}save();renderRoles();renderChat();$('#message-input').focus();toast(state.preview?'Message saved with a fixed preview. No AI response.':'Message saved locally. No reply generated.');};
  $('#preview-toggle').onchange=()=>{state.preview=$('#preview-toggle').checked;save();};
  $('#details-open').onclick=()=>{const role=active();$('#details-avatar').replaceChildren(avatar(role));$('#details-title').textContent=role.name;$('#details-subtitle').textContent=role.label;const body=$('#details-body');body.replaceChildren();const tags=node('div','scope-tags');for(const tag of role.tags)tags.append(node('span','',tag));body.append(tags);for(const [heading,text]of [['Accountable for',role.responsibility],['Expected deliverable',role.deliverable],['Handoff',role.handoff]])body.append(node('h3','',heading),node('p','',text));const imported=new Map(registry.currentFiles().map(f=>[f.path,f.text]));for(const ref of core.references(config).filter(r=>r.roleId===role.id)){const section=node('details'),heading=node('summary','',ref.kind+' · '+ref.path+' · text only, not activated'),text=node('pre','import-text',imported.get(ref.path)||'Not imported');section.append(heading,text);body.append(section);}const note=node('div','principle','Configured workflow role. No live model, running agent or external connection is configured.');note.prepend(icon('unplug'));body.append(note);$('#details-dialog').showModal();};
  const guides=[{"id": "openai", "title": "OpenAI / GPT", "description": "API access uses a Platform key and API billing separate from ChatGPT subscriptions. Eligible local/open-source integrations may support Sign in with ChatGPT plan usage; paid/remote apps require approval. Neither flow is implemented here, and no past chats are imported.", "console": "https://platform.openai.com/api-keys", "auth": "https://developers.openai.com/api/reference/overview", "models": "https://developers.openai.com/api/reference/resources/models/methods/list", "billing": "https://platform.openai.com/account/billing/overview", "extra": "https://developers.openai.com/siwc/token-sharing-open-source", "extraLabel": "Eligible Sign in with ChatGPT integrations"}, {"id": "anthropic", "title": "Anthropic / Claude", "description": "Use Claude API/Console access with API billing separate from consumer subscriptions. Third-party tools use API authentication; do not borrow Claude Code subscription tokens. Account access and model availability must be checked in the console.", "console": "https://platform.claude.com/settings/keys", "auth": "https://platform.claude.com/docs/en/manage-claude/authentication", "models": "https://platform.claude.com/docs/en/api/models/list", "billing": "https://support.claude.com/en/articles/9876003-i-have-a-paid-claude-subscription-pro-max-team-or-enterprise-plans-why-do-i-have-to-pay-separately-to-use-the-claude-api-and-console", "extra": "https://support.claude.com/en/articles/13189465-log-in-to-your-claude-account", "extraLabel": "Subscription token restrictions"}, {"id": "google", "title": "Google / Gemini", "description": "Use AI Studio to select/create/import a Cloud project and prepare an API key; review project quotas and Cloud Billing. A Google AI subscription is not automatic unlimited API allowance; developer credits may be separate. Project OAuth exists, but this app implements neither OAuth nor API authentication.", "console": "https://ai.google.dev/gemini-api/docs/api-key", "auth": "https://ai.google.dev/gemini-api/docs/oauth?hl=en", "models": "https://ai.google.dev/api/models", "billing": "https://ai.google.dev/gemini-api/docs/billing/", "extra": "https://ai.google.dev/gemini-api/docs/api-key", "extraLabel": "AI Studio project/key setup"}, {"id": "xai", "title": "xAI / Grok", "description": "Use the xAI console to prepare a team API key and review API credits/billing. Selected integrations support subscription OAuth (for example Kilo); a generally supported Rolequilt OAuth flow has not been established. No account connection is implemented here.", "console": "https://console.x.ai/home", "auth": "https://docs.x.ai/developers/quickstart", "models": "https://docs.x.ai/developers/rest-api-reference/inference/models", "billing": "https://docs.x.ai/console/billing", "extra": "https://x.ai/news/grok-kilocode", "extraLabel": "Selected subscription OAuth integration"}];
  function renderProviders(){
    const settings=$('#provider-settings');settings.replaceChildren();$('#provider-status').textContent='';
    for(const role of config.roles){const current=state.modelPreferences[role.id],row=node('section','provider-row'),heading=node('h4','',role.name+' · disconnected'),label=node('label','','Provider preference'),select=node('select'),modelLabel=node('label','','Unverified model ID (optional)'),input=node('input'),button=node('button','button-secondary','Save local preference');
      select.id='provider-'+role.id;label.htmlFor=select.id;for(const [id,name]of Object.entries(core.PROVIDERS)){const option=node('option','',name);option.value=id;select.append(option);}select.value=current.provider;
      input.id='model-'+role.id;modelLabel.htmlFor=input.id;input.type='text';input.maxLength=120;input.autocomplete='off';input.placeholder='Choose after connecting';input.value=current.modelId;
      select.onchange=()=>{if(select.value==='none')input.value='';};button.onclick=()=>{try{core.setModelPreference(state,config,role.id,{provider:select.value,modelId:input.value.trim()});save();$('#provider-status').textContent='Preference saved locally for '+role.name+'. Disconnected; model ID not verified.';}catch{$('#provider-status').textContent='Use a supported provider and a model ID up to 120 letters/digits/dots/hyphens/underscores/slashes. Not chosen requires an empty model ID. Do not enter credentials.';}};
      row.append(heading,label,select,modelLabel,input,button);settings.append(row);
    }
    const guide=$('#provider-guide');guide.replaceChildren();guide.append(node('p','','Use the provider’s developer account/API project. Consumer subscriptions must not be assumed to cover API usage. Exact account/billing steps and models depend on the provider and your account. This app has no login, key entry, OAuth flow or connection test.'));
    guide.append(node('p','','Official documentation checked by research on October 5, 2026. Account/model availability has not been tested. Keep keys/tokens out of this browser, demo and public repository. A future authenticated runtime would query your eligible model catalog; IDs entered above are unverified.'));
    for(const item of guides){const section=node('section','provider-guide-section');section.append(node('h4','',item.title),node('p','',item.description));const links=node('div','provider-links');for(const [label,url]of [['Open provider console',item.console],['Read authentication docs',item.auth],['Read model catalog docs',item.models],['Review billing',item.billing],[item.extraLabel,item.extra]]){const link=node('a','button-secondary',label);link.href=url;link.target='_blank';link.rel='noopener noreferrer';links.append(link);}section.append(links);guide.append(section);}
  }
  $('#providers-open').onclick=()=>{renderProviders();$('#providers-dialog').showModal();};$('#providers-close').onclick=()=>$('#providers-dialog').close();
  $('#details-close').onclick=$('#details-done').onclick=()=>$('#details-dialog').close();$('#reset-open').onclick=()=>$('#reset-dialog').showModal();$('#reset-cancel').onclick=()=>$('#reset-dialog').close();
  $('#reset-confirm').onclick=()=>{state=core.seedState(config);statusFilter='all';ownerFilter='all';$('#owner-filter').value='all';save();$('#reset-dialog').close();render();toast('Configured local state restored. Only this configuration was reset.');};
  for(const dialog of document.querySelectorAll('dialog'))dialog.addEventListener('click',e=>{if(e.target===dialog){const rect=dialog.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)dialog.close();}});
  const mobile=matchMedia('(max-width:760px)');
  function closeDrawer(){$('#app').classList.remove('drawer-open');$('#drawer-open').setAttribute('aria-expanded','false');$('#main-content').inert=false;$('#sidebar').inert=mobile.matches;}
  function closeAndFocus(){closeDrawer();$('#drawer-open').focus();}
  $('#drawer-open').onclick=()=>{$('#app').classList.add('drawer-open');$('#drawer-open').setAttribute('aria-expanded','true');$('#sidebar').inert=false;$('#main-content').inert=true;$('#drawer-close').focus();};$('#drawer-close').onclick=$('#drawer-backdrop').onclick=closeAndFocus;
  document.addEventListener('keydown',e=>{if(!$('#app').classList.contains('drawer-open'))return;if(e.key==='Escape')closeAndFocus();if(e.key==='Tab'){const items=[...$('#sidebar').querySelectorAll('button')].filter(b=>b.offsetParent!==null),first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
  mobile.addEventListener('change',()=>{const inDrawer=$('#sidebar').contains(document.activeElement);closeDrawer();if(mobile.matches&&inDrawer)$('#drawer-open').focus();});
  closeDrawer();render();if(loaded.recovered)toast('Unreadable saved demo state was restored to defaults.');
})();
